# SPDX-FileCopyrightText: (c) 2025 Crown Copyright, Government of Canada (Canadian Centre for Cyber Security / Communications Security Establishment)
# SPDX-License-Identifier: MIT
---
services:
  nte-suricata:
    build:
      context: .
      dockerfile: docker/Dockerfile-suricata
    volumes:
      - ./pcaps:/data/pcaps
      - ./logs:/data/logs
      - ./INFECTED:/data/INFECTED
